addons:
  sonarqube: true
language: java
jdk:
- oraclejdk8
before_install:
- cd events
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: heroku
  api_key:
    secure: VduYhI++vdxlgpA0YYVl0dhLeyiHdPdUDzmszhQXoM2+9GVL3yODhj/aUqnCVSqf54dEnQVxfezkGgXoFrtXdg4tzxveTAlaZ99tZXkiwL6DGBcwXH+QJcq4QKVecHTo5Fr/cyinZBt4Gye1QYE1Jhopkfgjy/DWF8YT+8ikv/LDlarEHgJjiu9RCXBwz9wM9ZoWK7SInimXhfqabgS+NTeKQMD+fTjCDI6OuDmT06xOP4UxoTVDtRxb6mJhfwp9257G2QR5vr8ENlsF8rwjnbxyavUklCzgBzKekK6hQmLHKNBpdf8v7bknFFg8+UdxW2+5Jbx1eedMoBaF5rOfGB3McdZyKqfov2px2i+EfGGGzA2vlpRHWi97WbrZaDj2rr2Rw7P9rRs80ibziMj3u+r1A2sNJS3DDfBVylIPfMRDQlL+iSY6bQQAMsh2tvRu8qq7WiqeFLTTl+rvcPam+evSzHJpY7+1bNCBmYNNNgVsNJtOlXfhlVZgXSUZFKN1ToV18ErFKuRmBPnazijJkb626AwhlIuL2DCb4yu5DRoyhNAlkPyoRCc0z7JWK54mbeL3+GLfHuLulTsoZKHXQpfjz4tYNTLxMcHLWDAuPcGtJxBe89w89APvj9/xvCTsvEs9tfUBsYax4O0kp2Nmv1FqZuDLn7XCVEqhEN/fJPA=
  app: apiondetemjogo
  on:
    repo: ondetemjogo/backend
cache:
  directories:
  - "$HOME/.m2/repository"
