language: java
jdk:
- oraclejdk8
before_install:
- cd events
script:
- mvn clean install
deploy:
  provider: heroku
  api_key:
    secure: aSxVR8ej8c0PssuoXXWZPWXhWfoOTonwXON22/ufG10fQDb0yo0YC0hvVqMMDWX505YxKFbFPRtOPnZ9MCoVcLCTb2uf+N5CaAn8D9uz/NibcDKYDzHE9D/O+ufzeh+tM9PlGYXZvPLZWZMiIjIYOuCqCmjeUHBTQ8YOLCvwko/Sue0v+EulN/KZIDHhHs6tzJHqzB0yCXCdz8RfshQOeva28q8zdVpKdlZw+6Wfsnp6DAUEzJlUVUyE22LHpbpGxwSgltSlAtEwRObUd9b5+alpjxqR92mc3dqHxNamMJkU/CtM3prihoGx8SIrUk3uvB8axZH4SQ566oXqVgl3n2OQ5aISyGAKdcBG8U5fFUJc7qSHu1UBJ8nTW6nn+G1jw5joz6Fa8e4ZaWd4wrQiP32HisEPUVh5//xydk0YiTLogXLhB/Fcq8L1S+lk3p/lgiU7zvmnfnV5LgF+hX5hhylDKEgshjxOlNJalfzXs0EPe//ai3n2RWIxKvIvi/cKfNpUnNMuC2ZMq2pVy6u+pv2wT6+KzPYiquJQskHv0swjKFpISL7uK4+c8I+vezPTN9wG0vw+7y5ZswJyyw+zxXW6+D//Z3Mo4bf1W7Ylt86KEyZFZhJJOAY4FnW77+oJ3wulX1coafDFy2+/mvb99R4fLKpWdDFruPe56hbRFXg=
  app: apiondetemjogo
  on:
    repo: ondetemjogo/backend
cache:
  directories:
  - "$HOME/.m2/repository"
