language: java
jdk:
- oraclejdk8
before_install:
- cd events
script:
- mvn clean install
deploy:
  provider: heroku
  api_key:
  - secure: "fPTn5jiGljG5KsBNQznj0p4R/u3nYltStCBqpH45SHrMHpy8+4NHLCeIpUHUO+3O2B94zfG7OF029A+P20SvCmD4Q9QRlqALIo8JxtVZfyiXeFAQiPO2/5QVdAGojtsXysMDw3KfaJd1ODmZv6oj1CMLf68RU7atm3GsX2w6KuFLH2fnAsOTAPEOs+idh7GGptoJwSpA5RnlYOrbPuRcPykQ0vizU/DRHOZdv3qIOZyZxWCT6b/g1nnJRFmpLsN4z15PXjFZZHJRypkZeHvC608f16ZeDvt24ELfTUOM29R8S9Uf2LuwU32m3YDp22eL2jAWPD2Dgr1kQUtSHOUbM5o7/YKgJ+TXpIEXMoUCFgP+Zq7ICh7Vl/5y+S0qlc82mLwh8DXMcohEzhxXYygFi+5Fk/VC5AUbszVSzBR8VNmM650P3UGyIjnWVHebVfqJ9meDsc3omSzlcvRtLdluqinQg44faZ/ZtL7Wl5Fh4BJiwxS3d4Gul+uZLN8yVwR71xBnei2nTER23p1Ru5uUjh6vUTeh93vSUL3KowUQBPaA3X9q0i1zVhzlWJAazU28u6W0zTl5EOaGUrMnEdgI8ep93jr71vU2POQfFvXkOuMw0Hqc5YuGO9MDBRCsxunsPAgo6jZZUzfii71DbiccE3QCRJW16SzfOGAzgZ8bDkg="
  app: apiondetemjogo
  on:
  - repo: ondetemjogo/backend
cache:
  directories:
  - "$HOME/.m2/repository"
