spring:
   jpa:
      database: POSTGRESQL
      generate-ddl: true
      hibernate:
         ddl-auto: update
      show-sql: true
   datasource:
      url: ${JDBC_DATABASE_URL}
      driver-class-name: org.postgresql.Driver
      spring.datasource.maxActive: 10
      maxIdle: 5
      minIdle: 2
      initialSize: 5
      removeAbandoned: true
   jackson:
      serialization:
         write-dates-as-timestamps: false
      serialization-inclusion: NON_NULL

server:
   port: 9000

logging:
   file: /home/ondetemjogo/starter.log
   
endpoints:
   cors:
      allowed-origins: http://localhost:8080/, http://ondetemjogo.herokuapp.com/, https://ondetemjogo.herokuapp.com/
      allowed-methods: GET,POST