spring:
   jpa:
      database: POSTGRESQL
      generate-ddl: true
      hibernate:
         ddl-auto: update
      show-sql: true
   datasource:
      url: ${JDBC_DATABASE_URL}
      driver-class-name: org.postgresql.Driver
      spring.datasource.maxActive=10
      maxIdle=5
      minIdle=2
      initialSize=5
      removeAbandoned=true

server:
   port: 9000

logging:
   file: /home/ondetemjogo/events.log