spring:
   jpa:
      generate-ddl: true
      hibernate:
         ddl-auto: update
      show-sql: true
   otj:
      datasource:
         driver-class-name: org.postgresql.Driver
         url: ${JDBC_DATABASE_URL}
         username: ${JDBC_DATABASE_USERNAME}
         password: ${JDBC_DATABASE_PASSWORD}

server:
   port: 9000

logging:
   file: /home/ondetemjogo/events.log